### ISSUE TITLE
Missing "allowMaximize" pane property

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#10]
## Is your feature request related to a problem? Please describe.
I would like to disable the maximize button on the pane's header

## Describe the solution you'd like
Add the "allowMaximize" property 

## Describe alternatives you've considered
ND

## Additional context
This is the button I want to disable
![image](https://user-images.githubusercontent.com/70320904/118135041-d87df600-b402-11eb-92ed-d08007ecd278.png)

**Comment by DiyanDimitrov** [comment]
@omanzelli, just to clarify - do you want to disable the maximize only for a specific pane and allow it for others?

**Comment by omanzelli** [comment]
@DiyanDimitrov Yes, like the "allowClose" for example.

**Comment by omanzelli** [comment]
is this available from version 1.5.0 ?

**Comment by DiyanDimitrov** [comment]
> is this available from version 1.5.0 ?

Yes, you can see it in the [changelog](https://github.com/IgniteUI/igniteui-dockmanager/blob/master/CHANGELOG.md).
