### ISSUE TITLE
Unpinned panel is closing automatically clicking on its content

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#11]
## Description  
Unpinned panel is closing automatically clicking on its content

![panel_close_automatically](https://user-images.githubusercontent.com/70320904/120215948-a956e980-c236-11eb-9c78-a87f5452c2f5.gif)

 * version: 1.4.1
 * browser: Chrome

## Steps to reproduce  
Please check the sample project
[https://codesandbox.io/s/ignite-ui-with-devextreme-filter-builder-issue-wqjvc](https://codesandbox.io/s/ignite-ui-with-devextreme-filter-builder-issue-wqjvc)

## Result  
The panel is closing automatically

## Expected result  
The panel remain opened clicking on its content

**Comment by omanzelli** [comment]
is this issue fixed with version 1.5.0 ?

**Comment by DiyanDimitrov** [comment]
> is this issue fixed with version 1.5.0 ?

Yes, you can see it in the [changelog](https://github.com/IgniteUI/igniteui-dockmanager/blob/master/CHANGELOG.md).
