### ISSUE TITLE
A floating pane is draggable outside of the page

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#14]
## Description  
A floating pane is draggable outside of the page

 * version: 1.5.0
 * browser: Chrome/Edge

## Steps to reproduce  

1. Set a pane as floating
2. Drag the pane outside of the page
3. Leave the pane 

## Result  
The pane is no more movable

## Expected result  
The pane should be kept inside the edges of the page.

## Attachments  
![lost_floating_panel](https://user-images.githubusercontent.com/70320904/123405966-aedfef00-d5aa-11eb-84ea-ef867f29800d.gif)

**Comment by astaev** [comment]
@omanzelli
This has been considered as an issue and has been fixed accordingly. The fix will be available at the next dockManager release.
Meanwhile, you can find a stackblitz sample which handles the paneDragOver event and set some drag restrictions(this is angular example, but the conception at other platforms is very similar) - https://stackblitz.com/edit/github-wtmqr4?file=src/app/dock-manager-sample/dock-manager.component.ts
