### ISSUE TITLE
Disable keyboard navigation shortcuts

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-dockmanager#22]
## Is your feature request related to a problem? Please describe.
I would like to disable the keyboard shortcuts in order to use them in a component that is contained in a pane.

## Describe the solution you'd like
Could be perfect to have a property to disable the shortcuts like `[keyboardShortcutsEnabled]="false"`

## Describe alternatives you've considered
Nope

**Comment by omanzelli** [comment]
Thanks @DiyanDimitrov!

I made a library that use this code
```
    private readonly KEY_CODE_A = 65;
    private readonly KEY_CODE_ARROW_L = 37;
    private readonly KEY_CODE_ARROW_R = 39;
    private readonly KEY_CODE_END = 35;
    private readonly KEY_CODE_START = 36;

    public oneKeyDown(event: KeyboardEvent) {
       
        // Select all with CTRL + A
        if (event.ctrlKey && event.keyCode === this.KEY_CODE_A) {
            event.stopPropagation();
            event.preventDefault();

        }

        // Select PREVIOUS with SHIFT + LEFT ARROW
        if (event.shiftKey && event.keyCode === this.KEY_CODE_ARROW_L) {
            event.stopPropagation();
            event.preventDefault();

        }

        // Select NEXT with SHIFT + RIGHT ARROW
        if (event.shiftKey && event.keyCode === this.KEY_CODE_ARROW_R) {
            event.stopPropagation();
            event.preventDefault();

        }

        // From current to the first
        if (event.shiftKey && event.keyCode === this.KEY_CODE_START) {
            event.stopPropagation();
            event.preventDefault();

        }

        // From current to the last
        if (event.shiftKey && event.keyCode === this.KEY_CODE_END) {
            event.stopPropagation();
            event.preventDefault();

        }

    }
```
The HTML
```
<div (keydown)="onKeyDown($event)">
</div>
```

I changed the HTML above adding `tabindex="-1"` so the `DIV` is now focusable.
Anyway, a property that enable/disable these shortcuts could be a very useful feature.

Thank you!

**Comment by omanzelli** [comment]
@DiyanDimitrov I found another problem regarding this request.
 
[Here a sample project](https://stackblitz.com/edit/github-jt4sfw-rxbypy?file=src/app/dock-manager-sample/column-selection/column-selection.component.ts)

Using keyboards' shortcuts on a text box for, for example, selecting the text, is not possible.

**Comment by DiyanDimitrov** [comment]
@omanzelli, This is because you are calling `preventDefault`, you should be calling only `stopPropagation`.

**Comment by omanzelli** [comment]
> @omanzelli, This is because you are calling `preventDefault`, you should be calling only `stopPropagation`.

So I must trap the keys on every pane?

**Comment by federicobenedetti** [comment]
@DiyanDimitrov simply put, in my application i want to choose whether those dockmanager's shortcuts are enabled or not :)
