### ISSUE TITLE
Disable the tab dynamically or programmatically

### ISSUE THREAD

**Issue by pavan6014** [IgniteUI/igniteui-dockmanager#23]
## Current Behavior
Disable the tab dynamically or programmatically is not happening.
Disable the tab is basic requirement of any frontend application, this feature is not provided with Ignite UI dock layout manager.

## Expected Behavior 
1) We should have provision to pass property to the configuration to disable tab based on rule set (like allowClose, allowDocking).
2) We should be able to disable the tab dynamically (using SetTimeout)

**Comment by gedinakova** [comment]
@mtsvyatkova Disabled pane can be selected via the tab group overflow menu.

**Comment by DiyanDimitrov** [comment]
We have added `disabled` property to the content pane in version `1.7.0`.
