### ISSUE TITLE
In RTL mode dock manager panes resize happens in the opposite direction of the mouse move

### ISSUE THREAD

**Issue by feliksmatsko** [IgniteUI/igniteui-dockmanager#24]
## Description  
In right-to-left mode, horizontal resizing of the panes in dock manager happens in the opposite direction of the mouse move

 * version: 1.6.0
 * browser: Chrome version 98.0.4758.80 (Official Build) (arm64)

## Steps to reproduce  

1. Create layout with dock manager and at least two panes
2. Add dir="rtl" attribute to the body tag
3. Try to resize dock panes horizontally

## Result  
Horizontal resizing of the panes happens in the opposite direction of the mouse move

## Expected result  
Horizontal resizing of the panes happens in the same direction of the mouse move

## Attachments  
[dock-manger-rtl-resize-issue.mp4.zip](https://github.com/IgniteUI/igniteui-dockmanager/files/8039842/dock-manger-rtl-resize-issue.mp4.zip)

**Comment by benej60** [comment]
Hi - just wondering about current status on this? We have a go-live coming up with a customer requiring RTL and this issue is the only one remaining we are waiting on, everything else is so far working perfectly for RTL layout.

**Comment by igdmdimitrov** [comment]
Hi @benej60. We will work on this next sprint.

**Comment by benej60** [comment]
Fantastic! Thanks so much for the quick response.
