### ISSUE TITLE
Customize dock manager panes and tabs

### ISSUE THREAD

**Issue by jvegaseg** [IgniteUI/igniteui-dockmanager#3]
## Is your feature request related to a problem? Please describe.
It is a feature request

## Describe the solution you'd like
In order to follow design style of our app, we need to customize in dock manager:

- Allow to configure custom CSS classes in order to make our custom tabs: rounded corners, borders, padding, etc.
- Allow to configure custom CSS classes in order to make pane headers customizable: rounded corners, borders, padding, etc.
- Allow to enable/disable Minimize/Maximize for each pane. It is not enough do it for all panes in the dock manager.
- Allow an easy way to add custom icons to the toolbar of pane and tab windows

**Comment by kaniete** [comment]
It would be nice this type of customization

**Comment by mmontes** [comment]
Hello, 

this would be awesome!

I need it in order to implement this design:

![image_2020_12_03T17_31_10_332Z](https://user-images.githubusercontent.com/4705288/101068262-c74dd500-3598-11eb-8472-4548a58a7876.png)


Regards,

**Comment by manasagrawalgsi** [comment]
Hello,

Do we have any update on this issue?

Regards,
Manas

**Comment by gedinakova** [comment]
Hello everyone,
Thank you for sharing your requirements.
Currently, only the third option for maximizing/minizing only certain panes is available for you to use. The other three customizations listed above should be possible in the next version we release.
