### ISSUE TITLE
Preserve the selected index before drag start

### ISSUE THREAD

**Issue by EddyNll** [IgniteUI/igniteui-dockmanager#31]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Lets say if you have 3 tabs on one pane: "tab a", "tab b" and "tab c".

If you select "tab a" and then drag "tab b" to a different pane, "tab c" is selected in the top pane.

The expected result would be that "tab a" would remain selected.

**Comment by igdmdimitrov** [comment]
Released in 1.13.0
