### ISSUE TITLE
Allow specifying minimum/maximum width of panels

### ISSUE THREAD

**Issue by parties** [IgniteUI/igniteui-dockmanager#32]
## Is your feature request related to a problem? Please describe.
I would like to be able to specify a minimum and/or maximum width (in pixels) for a specific panel.

## Describe the solution you'd like
A property on the panel (something like `minWidth`) that I can set programmatically as I declare the panel.

## Describe alternatives you've considered
I've tried listening to the change events for resizing, but since there's no way to set a width in pixels using JavaScript I cannot accomplish my end goal of: "This panel's width should never be less than 250px".

Being able to set a relative width (using the `size` property) isn't very useful, and I can't seem to reset this size parameter when handling re/size change events.

## Additional context
Repro of min-width issue with partial solution:
- https://codesandbox.io/s/min-width-repro-4iumvw
- I have tried a few different techniques for targeting panels and limiting their widths, but the only one that works is to target `igc-dockmanager::part(split-pane)` and `igc-dockmanager::part(content-pane)` with CSS; however this doesn't allow me to target a specific panel, I must target _all_ of the panels with this min-width style.
- Also, notice how you can drag the panel to be less than a certain width, however after dragging the panel's width to be less than the minimum when you try to maximize the panel again, it has to "make up the difference" between how far past the minimum you first dragged the panel. (This behavior seems to be a bit of a bug, on top of this missing behavior/feature of being able to specify a min/max width of a panel.)

Here is an example of what I am referring to:

https://user-images.githubusercontent.com/6612736/172913182-bafdd82d-8130-4d2e-8cc8-bf5ee4ab8488.mov

**Comment by D-Biela** [comment]
I'd love this feature too!

**Comment by igdmdimitrov** [comment]
New CSS parts added in v1.14.2. You can now target every pane by its `contentId` individually:

`igc-dockmanager::part(content1) {
  min-width: 350px;
}`
