### ISSUE TITLE
Dock Manager docs points to a 404 page

### ISSUE THREAD

**Issue by TrinTragula** [IgniteUI/igniteui-dockmanager#35]
## Description  
In Dock Manager (DM) docs [here](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager#api-members), the link to the api members section points to a [404 page](https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcdockmanagercomponent.html).
 * version: NA
 * browser: NA

## Steps to reproduce  

1. Navigate to https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager#api-members
2. Click the last link

## Results 

Actual, the DM link points to:
https://www.infragistics.com/products/ignite-ui-web-components/api/docs/typescript/latest/classes/igcdockmanagercomponent.html
Expected, the DM link points to
https://www.infragistics.com/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcdockmanagercomponent.html

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum please work on this issue (see TODO section)

**Comment by HUSSAR-mtrela** [comment]
it looks like all links to DM are hard-coded in markdown so I fixed this issue by hard-coding it for the broken link.
https://github.com/IgniteUI/igniteui-xplat-docs/commit/4facc31fe50156485df3c88637e0f5726ae6256a
