### ISSUE TITLE
'click' event on customized header buttons is not working

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-dockmanager#37]
## Description  
When having a custom button in the header part the **'click'** event is not working in Chrome, Opera, and Microsoft Edge. Currently, it is working in Firefox. In version 1.7.0 this is not reproducible and it is working for all browsers.

 * version: 1.9.0
 * browser: Chrome, Opera, Microsoft Edge

## Steps to reproduce  

1. Open this [demo](https://stackblitz.com/edit/dock-manager-resizing-tugqce?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.html).
2. Open the DevTools Console.
3. Click the button in Header 1.

## Result  
The **click** event is logged in the console currently **only in Firefox**.

## Expected result  
The **click** event should be logged in the console in all browsers.

**Comment by uatemycookie22** [comment]
also waiting on the fix. thank you guys you do great work! ❤️

**Comment by federicobenedetti** [comment]
Hi everyone! I see this issue is in 'resolved' state but without any mention to commit or PR. Any ETA? Thanks! :)

**Comment by igdmdimitrov** [comment]
Fix is now available in version `1.10.0`.
