### ISSUE TITLE
How to add custom buttons in the Dock manager Header?

### ISSUE THREAD

**Issue by vinityad** [IgniteUI/igniteui-dockmanager#38]
Basically, dock-manager provides only pin/unpin, Minimize/Maximize and close buttons in the header. I would like to add more custom button/s to the header. Is there any way to do it?

**Comment by igdmdimitrov** [comment]
Hi @vinityad . Sorry for the late reply. You can add buttons in the header content, but we don't have the option to add custom buttons in the `actions` area, which contains the pin, unpin and other buttons.
