### ISSUE TITLE
Docking not working with allowFloating: false

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-dockmanager#40]
## Description  
Panes with `allowFloating: false` can't be docked to any other pane.

 * version: 1.10
 * browser: Chrome

## Steps to reproduce
https://codesandbox.io/s/optimistic-sound-bfmu0j

There are 3 panes with `allowFloating: false`.
When you drag a pane and try to dock it on another pane then an error occurs.

**Comment by Timmeeeey** [comment]
I just found out this only happens when no floatingPanes are defined.

**Comment by igdmdimitrov** [comment]
Fix available in [v1.12.0](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.0)
