### ISSUE TITLE
Unpinned Content Pane flies out when interacting with some components within its content

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-dockmanager#41]
## Description  
When some components within an Unpinned Content Pane are clicked (the pane is active and focused at that time), then the pane loses focus, "flies out" and the active pane of the dock manager becomes unset.

The bahvior is similar to [this issue ](https://github.com/IgniteUI/igniteui-dockmanager/issues/11) fixed a while ago. 

 * version: 1.11.1, 1.11.0, 1.10.0
 * browser: tested with Chrome, Firefox, Edge

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igcdockmanager-comp-within-unpinned-pane-1-11-1?file=src/app/dock-manager-sample/dock-manager.component.html) sample
2. Open the top unpinned pane (header "Container.CentralDispatch")
3. Click on the "Clock" icon of the `igx-time-picker` component to open the time-picker overlay.

4. This behavior is not reproducible in version 1.9.0 - [sample](https://stackblitz.com/edit/igcdockmanager-comp-within-unpinned-pane-1-9-0?file=package.json).

## Result  
The pane on the background has been "flied out" and no active pane is set.

![1](https://user-images.githubusercontent.com/35433937/190637089-6a8c900a-e803-4e12-972d-ced2ae551492.png)

![2](https://user-images.githubusercontent.com/35433937/190637131-932a5e7b-4b6b-4c47-8214-6c7334272bf0.png)

Clicking on other test components, such as `IgxDropDown` and selecting an item, or selecting a date from an `IgxCalendar`, does not fly out the pane.

## Expected result  
The active pane to remain as is when interacting with components within its content, as in version 1.9.0.

**Comment by igdmdimitrov** [comment]
Fix available in [v1.12.0](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.0)
