### ISSUE TITLE
Focusable elements within Floating panes do not receive on click

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-dockmanager#42]
## Description  
Elements such as inputs or buttons are not receiving focus on click when a pane is floating. When docked, clicking results in focusing the elements as expected.

 * version: 1.11.1, probably any
 * browser: Tested in Chrome, Mozilla, Firefox

## Steps to reproduce  

1. Open [this](https://codesandbox.io/s/m8eit7?file=/src/index.ts) sample
2. Attempt to type in the number input in the "Accounts" pane.
3. Drag the "Accounts" pane to float it.
4. Attempt to type again.

Or, also reproducible in the dev sample component for the "Floating 2" pane hosting a simple input.

While this is reproducible in a node app, it is not in an Angular app with the `IgcDockManager` - sample [here](https://stackblitz.com/edit/igc-dock-manager-interactions-in-floating-window?file=src/app/dock-manager-sample/dock-manager.component.html).

## Result  
The input does not receive focus and the user is not able to type.

## Expected result  
Being able to type.
Workaround on application level - sample [here](https://codesandbox.io/s/igc-dock-manager-interactions-in-floating-window-workaround-fw8o53?file=/src/index.ts).

**Comment by federicobenedetti** [comment]
It doesn't work here too. Up! :)

**Comment by igdmdimitrov** [comment]
Fix available in [v1.12.0](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.0)
