### ISSUE TITLE
Why cant i change action button color and not just background color?

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-dockmanager#43]
## Description  
Describe the issue.

 * version: NA
 * browser: NA

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
It's a bit unclear from just the title what exactly you want to change, but assuming you want to change the text/background colors for buttons in the pane/tab headers, you can. 

[Here's an sample](https://stackblitz.com/edit/angular-8itujn?file=src/app/dock-manager-sample/dock-manager.component.scss) of how this can be achieved.

**Comment by amitmoondra** [comment]
this is exactly what i wanted, i looked for this in documentation could not find any. Please direct me there is any documentation for this.
thank you for assiting here.

**Comment by simeonoff** [comment]
Hi @amitmoondra, you can find a [list of all available parts here](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/dock-manager#css-parts).
