### ISSUE TITLE
include information about source pane in splitterResizeStart/splitterResizeEnd

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-dockmanager#44]
## Description  
When resizing a pane via the splitter, there is not any information included about the pane in the splitter resize events, e.g. width, height, etc. 

For example (compared with **floatingPaneResizeEnd**):

![dockmanager-events-demo](https://user-images.githubusercontent.com/49126110/200555077-34447ceb-49ef-4dbe-a7fc-74da7a27d11b.gif)

## Describe the solution you'd like 
Similar information to the one in the floatingPaneResizeStart/floatingPaneResizeEnd events should be included in the splitterResizeStart/splitterResizeEnd events.

**Comment by igdmdimitrov** [comment]
Fixed in [v1.12.1](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.1)
