### ISSUE TITLE
Question: can i use igx-charts instead of igc-charts(ignite-webcomponent) inside a content pane?

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-dockmanager#47]
I tried using igx-charts but it doesnot get rendered.
Is it,  that only igc-charts part of ignite-webcomponent library will only get rendered within the dock manager's content pane?

Please let me know your input here.

**Comment by igdmdimitrov** [comment]
@amitmoondra, `igniteui-angular-charts` can be used inside the `igniteui-dockmanager`. Here is a working sample - [Stackblitz](https://stackblitz.com/edit/angular-uusspk-qkaguc?file=src/app/area-chart-multiple-sources/category-chart-area-chart-multiple-sources.component.html). Let me know if this answers your question.
