### ISSUE TITLE
[Webcomponent/Blazor] Navigating with shortcut Alt+F7 does not bring the selected floating window to front

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-dockmanager#48]
1.Run the sample : https://codesandbox.io/s/github/IgniteUI/igniteui-wc-examples/tree/master/samples/layouts/dock-manager/overview?fontsize=14&hidenavigation=1&theme=dark&view=preview

2.Make one more pane floating (Tab2) and select it …notice ..selected floating pane is always on the top
Press ALT+F7 and switch between floating panes
 
3. issue is Selected floating pane is not on the top

Also a video for the steps to reproduce:
[https://1drv.ms/v/s!AtcMHKjRhnZxqM5fOlCqmU4K2jlG2Q?e=jhQryS](https://1drv.ms/v/s%21AtcMHKjRhnZxqM5fOlCqmU4K2jlG2Q?e=jhQryS)

Also logged this issue in the TFS274542

**Comment by igdmdimitrov** [comment]
Fix available in [v1.12.0](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.0)
