### ISSUE TITLE
Unable to focus input inside floating pane

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-dockmanager#50]
## Description  
The input within the floating pane is immediately losing focus when clicked making it impossible to type inside it.

 * version: 1.11.3
 * browser: Chrome 107.0.5304.107

## Steps to reproduce  

1. Run sample here: [https://codesandbox.io/s/winter-sound-901drt](https://codesandbox.io/s/winter-sound-901drt)
2. Make "Content Pane 1" float.
3. Click inside input element.

## Result  
The input is unable to obtain focus.

## Expected result  
The input obtains focus and user can type.

**Comment by igdmdimitrov** [comment]
Already fixed in develop branch.
