### ISSUE TITLE
How can I add scroll event on each content pane, i couldnot find any solution for this in documentation.

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-dockmanager#51]
<img width="599" alt="Screenshot 2022-11-29 at 2 57 35 PM" src="https://user-images.githubusercontent.com/20819281/204491059-bd9c1340-073a-4b60-b9c8-1ac588412ab0.png">

**Comment by amitmoondra** [comment]
@igdmdimitrov can you please respond here, i need to add some events on the scroll of content pane, but I am not able to do so right now.

**Comment by igdmdimitrov** [comment]
@amitmoondra, we don't have native support for this. If you would like us to treat this as a feature request, let us know what information do you need in the event detail.

**Comment by amitmoondra** [comment]
when is this scheduled to be released?

**Comment by radomirchev** [comment]
@amitmoondra our Q1 2023 pipeline is already full and we cannot commit any new features for that period. I will update the you once we scheduled it for development.

**Comment by amitmoondra** [comment]
@radomirchev is this getting released soon?

**Comment by igdmdimitrov** [comment]
@amitmoondra, yes, it will be released within a week.

**Comment by igdmdimitrov** [comment]
Added `paneScroll` event in [1.12.5](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.5). You can use the returned contentElement from `IgcPaneScrollEventArgs` to calculate if the content is scrolled to the bottom.
