### ISSUE TITLE
Pane that has its hidden property changed does not show until the dock manager is clicked

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-dockmanager#55]
Steps to Reproduce:

1. Run the attached sample project.
2. Close "Content Pane 1"
3. Click the button to set "Content Pane 1"'s hidden property to false.

Result:

Content Pane 1 does not show up. If you click on another pane in the IgcDockManager, it shows.
[overview.zip](https://github.com/IgniteUI/igniteui-dockmanager/files/10346160/overview.zip)

**Comment by igdmdimitrov** [comment]
@agoldenbaum , modifying the layout will not trigger an update. In order to do this you have to add `this.dockManager.layout = {...this.dockManager.layout};` in your event listener.
