### ISSUE TITLE
Cannot change default pane header buttons color 

### ISSUE THREAD

**Issue by federicobenedetti** [IgniteUI/igniteui-dockmanager#57]
## Description  
As you can see in this demo (https://codesandbox.io/s/unruffled-orla-1l5mk1?file=/src/DockManagerStyles.css), i cannot change the default color for pane headers buttons (such as maximise, minimize, close, ...)

 * version: latest (1.12.1)
 * browser: Chrome 108.0.5359.125

## Steps to reproduce  

1. go to the sandbox
2. check the styles applied (blue color and fill for the buttons)

## Result  
What is the actual result after following the steps to reproduce?
No color change visible

## Expected result  
What is the expected result after following the steps to reproduce?
Pane header buttons should change color to blue

## Attachments  
Attach a sample if available, and screenshots, if applicable.
![image](https://user-images.githubusercontent.com/26311786/211301347-099cf783-14bb-4d45-ae08-2e434fc26c1b.png)

**Comment by igdmdimitrov** [comment]
Hi @federicobenedetti. Take a look at this [Sample](https://stackblitz.com/edit/angular-8itujn?file=src/app/dock-manager-sample/dock-manager.component.scss)

**Comment by federicobenedetti** [comment]
Thank you very much! It works as expected, you can close this issue 👍🏻 
(i didn't see any of those scss variables in the official docs btw, but i could be wrong and i just simply missed them)

**Comment by igdmdimitrov** [comment]
I just checked and there seems to be no information about these variables in the docs, so we will log and fix this. Thank you!
