### ISSUE TITLE
Allow for showing/hiding unpinned flyout panes similar to hidden for pinned and floating panes 

### ISSUE THREAD

**Issue by iccrestron** [IgniteUI/igniteui-dockmanager#58]
## Is your feature request related to a problem? Please describe.
When panes are unpinned and a tab is created which can be clicked on to show or clicked away from to hide them, there is no way to control this programmatically. When a pane is pinned or floating, we can control them using the hidden property.

## Describe the solution you'd like
> Would like to see a method implemented explicitly for flying in / out a particular unpinned pane - direct quote from Infragistics Support thread

Was suggested that we create a feature request on GitHub

**Comment by igdmdimitrov** [comment]
Added method `focusPane` in v1.13.0
