### ISSUE TITLE
Maximised state of pane is not saved in the layout extract.

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-dockmanager#60]
## Description  
If i maximize a pane and then get the extract of layout to store it, the maximized state is not saved.

 * version: NA
 * browser: NA

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by igdmdimitrov** [comment]
Released in v1.13.0
