### ISSUE TITLE
Active pane incorrectly set when more than one Tab Group Pane is within a Floating Pane 

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-dockmanager#61]
## Description  
When a `SplitPane` having more than one `TabGroupPane` in its `panes` collection, is defined as a Floating Pane, there is an issue with activating the panes within the second (and others) tab groups.
 * version: latest
 * browser: any

## Steps to reproduce  

1. Open [this](https://codesandbox.io/s/igc-dockmanager-tab-group-pane-in-floating-38r2vp?file=/src/index.ts) sample and the CodeSandbox console.
2. Click anywhere on "Tab 1" to activate that tab.
3. Now click on "Tab 3".

## Result  
The "Tab 3" is activated for a moment, but then the active state is immediately reverted to "Tab 1" (or whichever tab was active within the first TabGroupPane in the Floating Pane). 
The activePaneChanged event handler outputs the following activated panes' headers:
```
Tab 3 
Tab 1 
```
## Expected result  
To be able to activate the "Tab 3" pane, or any pane within the second Tab Group Pane in the Floating Pane.

## Attachments  
![image](https://user-images.githubusercontent.com/35433937/220914734-ae764653-154b-4e30-bf09-35d84546fafd.png)

**Comment by binny-chopra** [comment]
Hi Team, do you have any updates on this issue ?
We are stuck in a major production issue. I request you to please process this bug a bit faster.

**Comment by igdmdimitrov** [comment]
@binny-chopra , this issue is scheduled for development and we will start working on it this week.

**Comment by binny-chopra** [comment]
@igdmdimitrov, I see this issue is in resolved state. Could you please share the version number which has this update?

**Comment by igdmdimitrov** [comment]
@binny-chopra , we are still doing some tests. Once we release a new version I will reply here with the version containing the fix.

**Comment by igdmdimitrov** [comment]
@binny-chopra , fix is released in [v 1.12.4](https://github.com/IgniteUI/dock-manager/releases/tag/1.12.4)

**Comment by binny-chopra** [comment]
@igdmdimitrov Thanks a lot. :)
