### ISSUE TITLE
Error in console after updating to 1.13

### ISSUE THREAD

**Issue by fexxdev** [IgniteUI/igniteui-dockmanager#79]
## Description  
Hi everyone
I'm using the latest version of dockmanager and simply put i have this error in the console when the dockmanager get loaded
![image](https://github.com/IgniteUI/igniteui-dockmanager/assets/26311786/f1791362-e636-453e-8de9-590f3dbf4369)

Unfortunately i haven't had enough time to look further. 
Although i can tell that's coming from the latest version, and the error is pretty self explanatory: 
![image](https://github.com/IgniteUI/igniteui-dockmanager/assets/26311786/1a425174-b787-4c92-984a-7cc6750b75e8)
Line 694. 
Can you please take a look at it? I'll update this thread as soon as i have more info to share.
Thanks!

 * version: 1.13
 * browser: Latest chrome

**Comment by onlyexeption** [comment]
@fexxdev,

I've tried reproducing the issue using an empty layout that just has a `rootPane` without any other panes and I noticed that the `paneParentMap` is still defined, even though its size is 0. Can you provide a sample reproducing the issue?
