### ISSUE TITLE
TabGroupPane disappears when an unpinned pane is pinned

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-dockmanager#84]
## Description  
TabGroupPane disappears when an unpinned pane is pinned

 * version: 1.14.2
 * browser: NA

## Steps to reproduce  

1. Run the attached sample dockmanager.zip.
2. Click “Tab 2” on the top right pane.
3. Click Unpin icon on the “Tab 2” header.
4. Click “Tab 2” tab.
5. Click Pin icon on the header.

## Result  
“Tab 2” disappears.

## Expected result  
“Tab 2” is pinned.

## Attachments  
Attach a sample if available, and screenshots, if applicable.
[dockmanager.zip](https://github.com/IgniteUI/igniteui-dockmanager/files/12654168/dockmanager.zip)
[dockmanager_pane_missing.zip](https://github.com/IgniteUI/igniteui-dockmanager/files/12654171/dockmanager_pane_missing.zip)

**Comment by gedinakova** [comment]
Resolved & released in 1.14.4.
