### ISSUE TITLE
Pane with allowPinning=false placed inside tab group can be unpinned

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-dockmanager#9]
## Description  
Pane with allowPinning=false placed inside tab group can be pinned.

 * version: NA
 * browser: NA

## Steps to reproduce  

1. Open https://infragistic-dock-manager.stackblitz.io/
2. Click the arrow button for the context menu of the 'Default' tab. 
3. Click Unpin.

## Result  
The pane is unpinned.

## Expected result  
Pane with allowPinning=false should not be unpinned. We should hide the context menu button if the pane cannot be closed and pinned.

**Comment by omanzelli** [comment]
@DiyanDimitrov do you know when this fix will be released?

**Comment by gedinakova** [comment]
@omanzelli It should be available by the end of this week!
