### ISSUE TITLE
Unpinned panes on the right and bottom edges cannot be resized via the splitter after being sized to minimum width/height

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-dockmanager#90]
## Description  
An unpinned pane is resized by dragging the splitter all the way until no further shrink is possible. After that, its size cannot be grown back by dragging the splitter.
This is the case for unpinned panes on the right edge - resizing in terms of width, and on the bottom edge - resizing in terms of height.

 * version: 1.14.0 onwards, not reproducible in 1.13.0
 * browser: any

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igc-dock-manager-resize-shrinked-unpinned-pane?file=src%2Fapp%2Fdock-manager-sample%2Fdock-manager.component.html) sample
2. Unpin "Content Pane 1"
3. Click on the unpinned header of "Content Pane 1" to fly the pane in.
4. Drag the splitter to the right to shrink the "Content Pane 1" until no further dragging is possible
5. Attempt to grow the pane back by dragging the splitter to the left direction

## Result  
It is not possible to increase the unpinned pane width back.

## Expected result  
To be able to shrink the pane width to the end and to be able to grow it back.

The same is behavior can be observed for unpinned panes on the bottom edge. On the upper one and left edges, when dragging down and to the right correspondingly, the size _can_ be increased.

## Attachments  
Unpinned panes on the right edge and on the bottom edge - unable to grow width/height back:
![dm-unpinned-panes-right-down](https://github.com/IgniteUI/igniteui-dockmanager/assets/35433937/fafeaaa0-2265-431d-95a2-7f5e1ae9c02a)

Unpinned panes on the upper edge and on the left edge - able to grow width/height back:
![dm-unpinned-panes-left-up](https://github.com/IgniteUI/igniteui-dockmanager/assets/35433937/0059a827-18a4-4d76-86fc-9d5bb59acdf4)

**Comment by gedinakova** [comment]
Resolved and released in 1.14.4.
