### ISSUE TITLE
Splitter cursor should be correct while resizing

### ISSUE THREAD

**Issue by sik-cloud** [IgniteUI/igniteui-dockmanager#93]
## Description  
Splitter cursor should be correct while resizing

 * version: 1.14.3
 * browser: Chrome

## Steps to reproduce  
See attachments  

## Result  
Cursor reverts to default state after start resizing.

## Expected result  
Cursor should be correct (horizontal/vertical arrows) during whole resize procedure

## Attachments  
![1](https://github.com/IgniteUI/igniteui-dockmanager/assets/22682744/758acce1-05cf-4366-965a-5ae7bde4d5af)

**Comment by agoldenbaum** [comment]
There was a support case opened for this issue recently, in which I tested to see if the issue was still reproducible. It is, and this appears to be a bug in the igc-dockmanager component. I have added an additional assignee to this issue @ChronosSF

**Comment by gedinakova** [comment]
@agoldenbaum Hi Andrew, I am trying to reproduce this with[ this sample](https://codesandbox.io/p/sandbox/github/IgniteUI/igniteui-wc-examples/tree/master/samples/layouts/dock-manager/overview?file=%2Fpackage.json%3A45%2C19&fontsize=14&hidenavigation=1&theme=dark&view=preview) without luck. Can you, please, add some repro steps and ideally a sample where you are able to achieve it? Thanks in advance.

**Comment by sik-cloud** [comment]
@gedinakova see attachments, it is straight forward reproduce

**Comment by igdmdimitrov** [comment]
@sik-cloud, @agoldenbaum, I was able to reproduce it. We will look into it.

**Comment by gedinakova** [comment]
Released in 1.15.0
