### ISSUE TITLE
Applying isMaximized on split pane breaks maximizing

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-dockmanager#95]
https://stackblitz.com/edit/rckq7s

Click maximize button that contains Document 1 and 2.

Result: nothing happens. 

Expected Result: Pane is maximized on load and can be toggled.

**Comment by gedinakova** [comment]
Hi Mike, we will inestigate this further to see why setting the property on a split pane breaks the layout, but for the time-being I recommend you move it to one of the content panes to get desired behavior. In general, I believe isMaximized is meant for the actual content and setting it on a split pane level doesn't make much sense, as with docking/undocking new split panes get created and certain settings can be lost. Hope this helps.

**Comment by gedinakova** [comment]
In our next patch, we will release a fix which:
- will make it possible to maximize/normalize panes whose parent split pane has its 'isMaximized' = true;
- will make sure setting the 'isMaximized' = true on either TabGroupPane or ContentPane will show them maximized as expected.
- will deprecate the 'isMaximized' property on IgcSplitPane.

**Comment by gedinakova** [comment]
Released in v1.14.4.
