### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'focus')

### ISSUE THREAD

**Issue by SC-Serhii-Litvinov** [IgniteUI/igniteui-dockmanager#96]
## Description  
Error appears in a console during pane closing
![image](https://github.com/IgniteUI/igniteui-dockmanager/assets/172475256/9c7c9a4e-c182-43d4-9058-c4f372081ca0)

 * version: 1.14.3
 * browser: Edge

## Steps to reproduce  
We have a requirement to allow user confirm or decline pane closing. To to achieve this we subscribe to `paneClose` event and do call `e.preventDefault()`.

After confirmation received we remove the pane. However if you click fast enough  to thing will happen. Note not all panes will require confirmation, some will just close without any additional user interaction. It' s impossible upfront to distingue between such panes. So prevent `preventDefault` is called for all panes.

1. Open few content panes
2. All panes should be closed without requiring user interaction
3. Try click on a pane after close button was pressed.
4. Observe the error in the console 

![image](https://github.com/IgniteUI/igniteui-dockmanager/assets/172475256/df3d01bd-3c12-48b1-8fd6-937096bbe894)
The cause of an issue is code inside `requestAnimationFrame`. `contentPanesElementMap` no longer contains requested pane. The pane had already been closed.

**UPDATE[17.06.2024]**
Sample application had been created to reproduce. In total there are three errors in this flow:
1. `handlePaneHeaderMouseDown`: _Cannot read properties of undefined (reading 'focus')_
2.  `closePane`: _Cannot read properties of undefined (reading 'type')_
3.  `bringFloatingPaneOnTop`: _TypeError: floatingPanes is not iterable_
It feels like all errors do have the same root cause

**Note:** in order to reproduce timing should be just right. Might not happen from the first attempt
![2024-06-17_16-49-15](https://github.com/IgniteUI/igniteui-dockmanager/assets/172475256/ee9906ac-862d-4688-9e1b-4e4771b518ff)

To reproduce: try closing **Floating Pane** via double clicking close button.
[Sample application link](https://stackblitz.com/edit/a3uxgv?file=src%2Fapp%2Fapp.component.ts)

## Result  
`Uncaught TypeError: Cannot read properties of undefined (reading 'focus')`

## Expected result  
The panel closed without errors in the console

**Comment by SC-Serhii-Litvinov** [comment]
Hi @gedinakova . Could you please share some details on how issue have been solved.

**Comment by gedinakova** [comment]
Hi @SC-Serhii-Litvinov, in essence we now make sure that after closing a floating pane we are not attempting to loop through a collection that is undefined. However, please note, that we closed this by mistake, as it will be released in the next DockManager version which should happen in the next 2 weeks.

**Comment by SC-Serhii-Litvinov** [comment]
You are still relying on `requestAnimationFrame` to process events, am I right?

**Comment by gedinakova** [comment]
Yes, we do, that hasn't changed.
