### ISSUE TITLE
Layout has more nesting levels then should

### ISSUE THREAD

**Issue by sik-cloud** [IgniteUI/igniteui-dockmanager#97]
## Description  
Layout has more nesting levels then should

 * version: 1.14.3
 * browser: Chrome

## Steps to reproduce  

1. Open [codepen](https://codesandbox.io/p/sandbox/pedantic-satoshi-zjx42q)
2. Click **Get Layout** button
3. Dock **Content pane 2** to the left side of the screen
4. Click **Get Layout** button
5. Dock **Content pane 2** to the bottom side of the screen
6. Click **Get Layout** button

## Result  
The final layout becomes more complicated and has more nesting levels as it was at the beginning. So, now I need to flatten split panes with only one child inside to make the layout cleaner and not to pollute my external storage.

## Expected result  
The final layout should be absolutelly the same as on the beginning

## Attachments  
![1](https://github.com/IgniteUI/igniteui-dockmanager/assets/22682744/832709e6-1238-4cc7-a640-1f74302d96f4)

**Comment by gedinakova** [comment]
@sik-cloud Thank you for the detailed report. We've scheduled this for development and we'll let you know when a fix is released!

**Comment by gedinakova** [comment]
Released in 1.15.0
